

w2w = {
	'lets': 'let us',
	'djou': 'do you',
	'd\'you': 'do you',
	'didjou': 'did you',
	'wouldjou': 'would you',
	'whadyou': 'what do you',
	'whaddya': 'what do you',
	'whadya': 'what do you',
	'didja': 'did you',
	'gimme': 'give me',
	'comere': 'come here',
	'c\'mere': 'come here',
	'cmere': 'come here',
	'camere': 'come here',
	'c\'mon': 'come on',
	'comon': 'come on',
	'lookee': 'look',
	'looka': 'look',
	'mkay': 'okay',
	'whyn\'t': 'why do not you',
	'ya': 'you',
	'til': 'until',
	'untill': 'until',
	'gon na': 'going to',
	'goin': 'going',
	'havta': 'have to',
	'have_to': 'have to',
	'oughta': 'ought to',
	'd\'ya': 'do you',
	'doin': 'doing',
	'cann\'t': 'can not',
	'dontcha': 'do not you',
	'getcha': 'get you',
	'howbout': 'how about',
	'scuse': 'excuse',
	'y\'know': 'you know',
	'ai n\'t': 'is not',
	'\'cause': 'because',
	's\'more': 'some more',
	'got_to': 'got to',
	'got ta': 'got to',
	'aroun': 'around',
	'what s': 'what is',
}