

FICTIONAL = {
    'pink eddie',
    'gonga',
    'koala',
    'sleeping beauty',
    'beauty',
    'toot',
    'puddle',
    'sleepy bear',
    'dopey',
    'little engine',
    'little bear',
    'little bird',
    'red riding hood',
    'stuart little',
    'little foot',
    'yogi bear'
    'nursie nellie',
    'tunky winky',
    'willy wonka',
    'daffy duck',
    'easter bunny',
    'harry potter',
    'raggedy ann',
    'raggedy andy',
    'old macdonald',
    'old mcdonald',
    'kitty cat',
    'richard scarry',
    'darth vader',
    'anakin skywalker',
    'luke skywalker',
    'mary beth',
    'mary ann',
    'humpty dumpty',
    'adam smith',
    'aunt ada',
    'amelia bedelia',
    'mr rogers',
    'mister rogers',
    'mrs rogers',
    'miss rogers',
    'rodger rabbit',
    'roger rabbit',
    'topham hatt',
    'dumbo',
    'ariel',
    'elmo',
    'bert',
    'ernie',
    'santa_claus',
    'santa claus',
    'santie claus',
    'robin',
    'mickey',
    'donald',
    'cinderella',
    'grover',
    'maisy',
    'snoopy',
    'miffy',
    'clifford',
    'cookie_monster',
    'cookie monster',
    'buzz lightyear',
    'buzz_lightyear',
    'buzz',
    'peanuts',
    'cranky',
    'kit',
    'bozo',
    'tom',
    'jerry',
    'frog',
    'king kong',
    'toad',
    'hulk',
    'paddington',
    'harry',
    'harry_potter',
    'simba',
    'piglet',
    'bunny money',
    'funny bunny',
    'pj funny bunny',
    'leo',
    'goofy',
    'tigger',
    'minnie',
    'minnie mouse',
    'minnie_mouse',
    'minney mouse',
    'mousey_nouse',
    'birthday_bear',
    'birthday bear',
    'corduroy',
    'bugs',
    'bugs bunny',
    'bugs_bunny',
    'dora',
    'mcdonald',
    'nemo',
    'nursie_nellie',
    'froggie',
    'eeyore',
    'horton',
    'alice',
    'jay jay',
    'snuffy',
    'spiderman',
    'lass',
    'Gepetto',
    'huckle',
    'loly',
    'pinocchio',
    'barney',
    'fred',
    'dorothy',
    'wilbur',
    'bambi',
    'jesus',
    'batman',
    'mickey_mouse',
    'chester',
    'mufasa',
    'goldilocks',
    'humpty_dumpty',
    'itsy bitsy',
    'itsy_bitsy',
    'itsy',
    'simple_simon',
    'popeye',
    'goldie',
    'dipsy',
    'tunky_winky',
    'lincoln',
    'lassie',
    'old macdonald',
    'old mcdonald',
    'sully',
    'sulley',
    'raggedy_ann',
    'raggedy_andy',
    'kermit',
    'grouchy',
    'zach',
    'zeek',
    'willy_wonka',
    'pebbles',
    'bam_bam',
    'raffi',
    'rusty',
    'donald_duck',
    'donald duck',
    'easter_bunny',
    'scuffy',
    'daffy',
    'daffy_duck',
    'big_bird',
    'dingo',
    'fixit',
    'gordon',
    'percy',
    'care_bear',
    'superman',
    'super man',
    'bat man',
    'spider man',
    'green goblin',
    'e_t',
    'yoda',
    'blitzen',
    'rudolph',
    'he_man',
    'vik',
    'chewbacca',
    'motorcycle chicken',
    'elmer',
    'coco',
    'alouette',
    'pig',
    'pa pig',
    'penelope pig',
    'p s pig',
    'floppy',
    'bear',
    'care bear',
    'brother bear',
    'winnie_the_pooh',
    'winnie pooh',
    'winnie',
    'pooh'
    'winnie_pooh',
    'pooh bear'
    'winnie_the_pooh',
    'potato',
    'mr potato_head',
    'potato_head',
    'potatohead',
    'potato+head',
    'mister_potatohead',
    'mister_potato_head',
    'mr_potatohead',
    'mister_potato',
    'piglet',
    'otto',
    'noah',
    'nala',
    'hendrika',
    'gaspard',
    'lisa',
    'darth_vader',
    'charlotte',
    'mr_potato_head',
    'snow_white',
    'snow white',  # doesn't work if either is not title-cased
    'ivory snow',
    'rafiki',
    'lola',
    'benjamin',
    'shamu',
    'aurora',
    'amelia_bedelia',
    'bloat',
    'R_two_D_two',  # title-case must match exactly
    'rapunzel',
    'skywalker',
    'flintstones',
    'topham_hatt'
    'bruno',
    'bruno bear',
    'bangus',
    'bangus bear',
    'big bird',
    'scar',
    'puddy',
    'tupty',
    'brenda blue',
    'flounder',  # a fish character
    'moo',
    'lowly',
    'ali cat',
    'kanga',
    'roo',
    'swiper',  # the fox
    'ears',  # mr ears
    'piggy',
    'jasmine',
    'jay joe jeans',
    'captain fishhead',
    'captain bob',
    'boots',  # a monkey
    'chatty_baby',
    'tig',
    'Shadow_Gay',
    'humm',
    'carrots',
    'papa smurf',
}

NICKNAMES = {
    'honey',
    'hon',
    'sweetie',
    'sweetiepie',
    'sweetie_poo',
    'sweetie_petey',
    'sweetie_peteetie',
    'booboo',
    'curly shirley',  # a doll
    'alligator',  # mr alligator
}

PETS = {
    'tiki',
    'sugar',
    'rocky',
    'tramp',
}

REAL = {
    'Joseph_P',
    'tickles',
    'helga',
    'lise menn',
    'lise',
    'gammy',
    'ush',
    'jay',
    'davis',
    'willy',
    'julie',
    'kristen',
    'carol',
    'don'
    'lady',
    'guy',
    'kay',
    'roman',
    'bax',
    'sesame',
    'wood',   # mrs wood
    'el',
    'po',
    'teddy',
    'will',
    'gail',
    'daisy'
    'patsy'
    'ernest'
    'laura',
    'mama',
    'sarah',
    'william',
    'ross',
    'adam',
    'nomi',
    'naima',
    'abe',
    'alex',
    'lily',
    'peter',
    'nina',
    'ethan',
    'nathaniel',
    'eve',
    'marky',
    'mark',
    'violet',
    'max',
    'paul',
    'sally',
    'thomas',
    'manuela',
    'michael',
    'ursula',
    'matthew',
    'melissa',
    'kalie',
    'pete',
    'bob',
    'jenny',
    'eric',
    'nana',
    'david',
    'matty',
    'travis',
    'fraser',
    'megan',
    'sam',
    'rachel',
    'amanda',
    'john',
    'jack',
    'pat',
    'george',
    'olivia',
    'erin',
    'ryan',
    'judy',
    'lois',
    'trevor',
    'joseph',
    'jennifer',
    'mary',
    'franklin',
    'emily',
    'phoebe',
    'katie',
    'cromer',
    'charlie',
    'brittany',
    'kent',
    'linda',
    'emma',
    'mike',
    'arthur',
    'nonna',
    'andrew',
    'patrick',
    'oscar',
    'maggie',
    'sophie',
    'harold',
    'james',
    'seth',
    'richard',
    'jessica',
    'hilda',
    'jilly',
    'gigi',
    'georgie',
    'oliver',
    'bill',
    'karen',
    'chantilly',
    'jill',
    'jamie',
    'danny',
    'gerry',
    'rosie',
    'henry',
    'kate',
    'joe',
    'lisa',
    'aislinn',
    'laurie',
    'sandy',
    'lulu',
    'catherine',
    'donna',
    'colin',
    'spencer',
    'joey',
    'matt',
    'becky',
    'anne_marie',
    'belle',
    'lucy',
    'chris',
    'billy',
    'jane',
    'brian',
    'liam',
    'gordon',
    'nancy',
    'ma',
    'polly',
    'andy',
    'ben',
    'steve',
    'norman',
    'kim',
    'joanna',
    'jillian',
    'gloria',
    'elizabeth',
    'betty',
    'gabby',
    'courtney',
    'ann',
    'naomi',
    'nat',
    'tadi',
    'luke',
    'debbie',
    'kathy',
    'frank',
    'stefan',
    'patty',
    'annie',
    'tommy',
    'sean',
    'daniel',
    'fred',
    'stella',
    'marie',
    'graham',
    'christopher',
    'bobby',
    'j_j',
    'becca',
    'jenell',
    'millisandy',
    'toddy',
    'lynn',
    'vaivy',
    'johnny',
    'jimmy',
    'bobo',
    'jen',
    'miriam',
    'janet',
    'sandra',
    'cathy',
    'zoe',
    'martin',
    'ari',
    'barbara',
    'anne',
    'jerry',
    'wilson',
    'tamar',
    'frederick',
    'toby',
    'helen',
    'elliot',
    'jesse',
    'dan',
    'tippy',
    'mrs_gwww',
    'diandra',
    'ted',
    'leslie',
    'elana',
    'sara',
    'harvey',
    'eddie',
    'sammy',
    'renee',
    'mimi',
    'justin',
    'jonathan',
    'erica',
    'wendy',
    'susie',
    'nathan',
    'nanette',
    'ellie',
    'leila',
    'joshua',
    'douglas',
    'alec',
    'jim',
    'isabelle',
    'charles',
    'tony',
    'julia',
    'zack',
    'patricia',
    'katy',
    'griz',
    'dick',
    'danielle',
    'usher',
    'steven',
    'sharon',
    'meg',
    'marty',
    'edna',
    'weist',
    'susan',
    'stephen',
    'stan',
    'salley',
    'felix',
    'carl',
    'theo',
    'liza',
    'kirsten',
    'heidi',
    'esther',
    'dale',
    'dabee',
    'terry',
    'rossy',
    'ronnie',
    'lia',
    'cindy',
    'amy',
    'tyler',
    'murphy',
    'fredrick',
    'brenda',
    'bobby',
    'aunt_dot',
    'willie',
    'franny',
    'ema',
    'craig',
    'cara',
    'butch',
    'brendon',
    'theresa',
    'sully',
    'nicky',
    'michelle',
    'gus',
    'aunt_carey',
    'wanda',
    'donny',
    'baxter',
    'molly',
    'larry',
    'ian',
    'jean',
    'hank',
    'betsy',
    'avril',
    'ais',
    'titus',
    'tallulah',
    'shaun',
    'rex',
    'pattycake',
    'mel',
    'lou',
    'gerald',
    'aladar',
    'shana',
    'maryse',
    'loi',
    'lilly',
    'lee',
    'gaby',
    'frannie',
    'weener',
    'brown',
    'baaee',
    'boo',
    'evan',
    'aaron',
    'nicholas',
    'marissa',
    'lil',
    'awoh',
    'ruby',
    'sue',
    'ann_marie',
    'didldow',
    'yaya',
    'hunm',
    'mike',
    'uncle_bwww',
    'mrs_gwww',
    'stef',
    'scott',
    'rory',
    'josh',
    'jo_ann',
    'eddy',
    'anthony',
    'robert',
    'olie',
    'nick',
    'lucille',
    'lindsay',
    'greg',
    'timmy',
    'pierre',
    'jeff',
    'alexander',
    'abbie',
    'julius',
    'd_w',
    'louise',
    'gilly',
    'cassandra',
    'agra',
    'todd',
    'timothy',
    'moby',
    'malik',
    'joseph_p',
    'kimberly',
    'jenko',
    'ericka',
    'amelia',
    'allison',
    'nora',
    'carey',
    'blanche',
    'uncle_ryan',
    'tegama',
    'tanta',
    'paula',
    'panacka',
    'lewis',
    'kenny',
    'keith',
    'jackie',
    'gabi',
    'diane',
    'babykins',
    'asha',
    'rolf',
    'petey',
    'mormor',
    'izzy',
    'ines',
    'ellen',
    'edward',
    'drew',
    'dayja',
    'celia',
    'buster',
    'betta',
    'amye',
    'zoey',
    'veena',
    'pushpa',
    'samantha',
    'margaret',
    'cassie',
    'dot',  # aunt and also princess dot from bug's life
}

FAMILY = {
    'mom',
    'dad',
    'grandma',
    'granddad',
    'aunt',
    'uncle',
    'mommy',
    'momma',
    'mom',
    'mama',
    'mamma',
    'mumma',
    'mummy',
    'mum',
    'papa',
    'dad',
    'daddy',
    'dada',
    'babaji',
    'dadaji',
    'badji',
    'grandma',
    'granma',
    'grandmama',
    'great grandma',
    'great+grandma',
    'Great_Grandma',
    'Greatgrandma',
    'nonno',
    'gramma',
    'gran',
    'granny',
    'grammy',
    'grandpa',
    'grampa',
    'granda',
    'granddad',
    'grandpere',
    'grampy',
    'grandaddy',
    'auntie',
    'untie',
    'santy_claus',
    'toppumhat',
    'toppemhat',
    'toppenhat',
}



